# Generated by Django 5.1.2 on 2024-10-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preCorrecao", "0002_cidade_estado_delete_dadosdoscampos_cidade_estado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cidade",
            old_name="nome",
            new_name="nomeCidades",
        ),
    ]
